export { Dashboard } from './Dashboard'
export { Login } from './Login'
export { Categories } from './Categories'
export { Attributes } from './Attributes'
export { Reviews } from './Reviews'
export { Products } from './products/Products'
export { CreateProduct } from './products/CreateProduct'
export { UpdateProduct } from './products/UpdateProduct'